server:
  port: 0

spring:
  application:
    name: ATTENDANCE_SERVICE
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token:
      kv:
        enabled: true
        backend: secret
        default-context: database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attendance_service?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: false

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        cloud:
          vault: DEBUG
