server:
  port: 0

spring:
  profiles:
    active: vault
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: false

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        cloud:
          vault: DEBUG
