spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://AUTH_SERVICE
            predicates:
              - Path=/auth/**
            filters:
              - JwtFilter

          - id: attendance-service
            uri: lb://ATTENDANCE_SERVICE
            predicates:
              - Path=/attendance/**
            filters:
              - JwtFilter

          - id: category-service
            uri: lb://CATEGORY_SERVICE
            predicates:
              - Path=/categories/**
            filters:
              - JwtFilter

          - id: user-service
            uri: lb://USER_SERVICE
            predicates:
              - Path=/users/**
            filters:
              - JwtFilter

          - id: eureka-service
            uri: lb://SERVICE_REGISTRY
            predicates:
              - Path=/eureka/**

  application:
    name: API_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

free-resources:
  urls:
    - "lb://AUTH_SERVICE/auth/login"
    - "lb://USER_SERVICE/users/register"
    - "lb://SERVICE_REGISTRY/eureka/**"

