spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH_SERVICE
          predicates:
            - Path=/auth/**

        - id: attendance-service
          uri: lb://ATTENDANCE_SERVICE
          predicates:
            - Path=/attendance/**

        - id: category-service
          uri: lb://CATEGORY_SERVICE
          predicates:
            - Path=/categories/**

        - id: user-service
          uri: lb://USER_SERVICE
          predicates:
            - Path=/users/**

        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  application:
    name: API_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

free-resources:
  urls:
    - "lb://AUTH_SERVICE/auth/login"
    - "lb://USER_SERVICE/users/register"
    - "http://localhost:8761/eureka/**"

