spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: attendance-service
            uri: lb://ATTENDANCE_SERVICE
            predicates:
              - Path=/attendance/**
            filters:
              - AuthenticationFilter

          - id: category-service
            uri: lb://CATEGORY_SERVICE
            predicates:
              - Path=/categories/**
            filters:
              - AuthenticationFilter

          - id: user-service
            uri: lb://USER_SERVICE
            predicates:
              - Path=/users/**
            filters:
              - AuthenticationFilter

  application:
    name: API_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

