spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://AUTH_SERVICE
            predicates:
              - Path=/auth/**
            filters:
              - AuthenticationFilter

          - id: attendance-service
            uri: lb://ATTENDANCE_SERVICE
            predicates:
              - Path=/attendance/**
            filters:
              - JwtFilter

          - id: category-service
            uri: lb://CATEGORY_SERVICE
            predicates:
              - Path=/categories/**
            filters:
              - JwtFilter

          - id: user-service
            uri: lb://USER_SERVICE
            predicates:
              - Path=/users/**
            filters:
              - JwtFilter

          - id: eureka-service
            uri: lb://SERVICE_REGISTRY
            predicates:
              - Path=/eureka/**

  application:
    name: API_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

free-resources:
  urls:
    - "/auth/login"
    - "/users/register"
    - "/eureka/**"

authenticated-resources:
  urls:
    - "/users/**"
    - "/categories/**"
    - "/attendance/**"

admin-resources:
  urls:
    - "/users/**"
    - "/categories/**"
    - "/attendance/**"
    - "/auth/**"

checker-resources:
  urls:
    - "/categories/*/assign"
    - "/attendance/user/{userId}"
    - "/attendance/category/{categoryId}"

attendant-resources:
  urls:
    - "/attendance/user/{userId}"
    - "/attendance/category/{categoryId}"

