server:
  port: 0

spring:
  application:
    name: USER_SERVICE
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token:
      kv:
        enabled: true
        backend: secret
        default-context: database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    username: myuser
    password: secret

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/