server:
  port: 0

spring:
  application:
    name: AUTH_SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

free-resources:
  urls:
    - "/auth/login"
    - "/auth/validate"
    - "lb://USER_SERVICE/users/register"
    - "http://localhost:8761/eureka"

authenticated-resources:
  urls:
    - "/auth/logout"
    - "/auth/blacklist/check"
    - "lb://USER_SERVICE/users"
    - "lb://USER_SERVICE/users/{id}"
    - "lb://USER_SERVICE/users/{username}"
    - "lb://USER_SERVICE/users/{id}/status"
    - "lb://USER_SERVICE/users/status"
    - "lb://ATTENDANCE_SERVICE/attendance"
    - "lb://ATTENDANCE_SERVICE/attendance/user/{userId}"
    - "lb://ATTENDANCE_SERVICE/attendance/category/{categoryId}"
    - "lb://CATEGORY_SERVICE/categories/{id}"

admin-resources:
  urls:
    - "lb://USER_SERVICE/users/**"
    - "lb://ATTENDANCE_SERVICE/attendance/**"
    - "lb://CATEGORY_SERVICE/categories"
    - "lb://CATEGORY_SERVICE/categories/{id}"
    - "lb://CATEGORY_SERVICE/categories/{id}/assign"

checker-resources:
  urls:
    - "lb://CATEGORY_SERVICE/categories/{id}/assign"
    - "lb://ATTENDANCE_SERVICE/attendance/user/{userId}"
    - "lb://ATTENDANCE_SERVICE/attendance/category/{categoryId}"

attendant-resources:
  urls:
    - "lb://ATTENDANCE_SERVICE/attendance/user/{userId}"
    - "lb://CATEGORY_SERVICE/categories/{id}"

