server:
  port: 0

spring:
  application:
    name: NOTIFICATION_SERVICE
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token:
      kv:
        enabled: true
        backend: secret
        default-context: mail
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: ${mail.username}
    password: ${mail.password}
  rabbitmq:
    username: myuser
    password: secret

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
