server:
  port: 0

spring:
  application:
    name: CATEGORY_SERVICE
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token:
      kv:
        enabled: true
        backend: secret
        default-context: database
  data:
    mongodb:
      uri: ${mongo.uri}
  rabbitmq:
    username: myuser
    password: secret

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
