server:
  port: 8082

spring:
  application:
    name: CATEGORY_SERVICE
  data:
    mongodb:
      uri: mongodb+srv://root:12345@veso.j5wqi.mongodb.net/user_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
